name: Backend CI

# Only run on changes to backend directories
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        working-directory: backend
        run: uv sync

      - name: Start server
        working-directory: backend
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: uv run fastapi run src/main.py &

      - name: Check server is running
        run: |
          curl --retry 5 --retry-delay 2 --retry-connrefused --fail http://127.0.0.1:8000/docs
